baseURL = "https://rkuzsma.github.io/resume/"
languageCode = "en-us"
title = "About"
theme = "bare-hugo-theme"
enableGitInfo = true
publishDir = "docs"

[taxonomies]
  tag = "tags"
  series = "series"

[params]
mainSections = ["post"]
author = "Rich Kuzsma"
email = "rkuzsma@gmail.com"
repoLink = "https://github.com/rkuzsma/resume"
description = 'Coaching engineers. Building products. Getting stuff done.'
# PostCSS is harder than it should be to get working on a theme
# example site. It's easy on _your_ site.
postcss = false
# Include the author name in the <title> of articles
includeAuthorInTitle = true
favicon = 'favicon.ico'

[[params.social]]
icon = "github-circle"
url = "https://github.com/rkuzsma/"

[[params.social]]
icon = "github-circle"
url = "https://github.com/richkuz/"

[[params.social]]
icon = "linkedin"
url = "https://linkedin.com/in/rich-kuzsma/"

[[params.social]]
icon = "stack-overflow"
url = "https://stackoverflow.com/users/2312060/rich-kuzsma"
